version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    on:
      push:
        branches:
          - master

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    on:
      schedule:
        - cron: "0 0 * * *"
